### ISSUE TITLE
Issue with UglifyJS while packing production build

### ISSUE THREAD

**Issue by daformat** [dzcpy/transliteration#28]
Hello,

I have no problem using transliterate in my dev environment, however, when I try to generate my production build I get an error with webpack 2 UglifyJS plugin complaining about `codemap`:

```
ERROR in /app-1b68d4b985561a4f9537.js from UglifyJs
SyntaxError: Unexpected token: name (codemap) [/app-1b68d4b985561a4f9537.js:4079,4]
```

I'm using react (es6) and I'm importing the transliterate helper via:
`import {transliterate} from 'transliteration/src/main';`

I couldn't get any other method described in the README for the import to work.

Using node v7.4.0 (with npm  v4.1.2)

Is there something I'm missing? Eagerly waiting for you insights ^^

**Comment by daformat** [comment]
I ended up using my own basic transliteration function until I find the correct way to use this one:

```javascript
/* Basic transliteration helper */
function transliterate(str) {
  return str.replace(/[ÀÁÂÃÄÅ]/g, 'A')
    .replace(/[Æ]/g, 'AE')
    .replace(/[Ç]/g, 'C')
    .replace(/[ÈÉÊË]/g, 'E')
    .replace(/[ÌÍÎÏ]/g, 'I')
    .replace(/[Ñ]/g, 'N')
    .replace(/[ÒÓÔÕÖ]/g, 'O')
    .replace(/[Œ]/g, 'OE')
    .replace(/[ÙÚÛÜ]/g, 'U')
    .replace(/[ÝŸ]/g, 'Y')
    .replace(/[àáâãäå]/g, 'a')
    .replace(/[æ]/g, 'ae')
    .replace(/[ç]/g, 'c')
    .replace(/[èéêë]/g, 'e')
    .replace(/[ìíîï]/g, 'i')
    .replace(/[ñ]/g, 'n')
    .replace(/[òóôõö]/g, 'o')
    .replace(/[œ]/g, 'oe')
    .replace(/[ùúûü]/g, 'u')
    .replace(/[ýÿ]/g, 'y');
}
```

**Comment by andyhu** [comment]
Hi @daformat,
Can you provide more information like the config of your webpack and a test code that I can reproduce it?
Also, have you tried to directly import from transliteration module like below:
`import transliterate from 'transliteration';`?

**Comment by daformat** [comment]
Sure, here is the important part of my webpack config (for prod):

```javascript
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        unused: true,
        dead_code: true // eslint-disable-line camelcase
      },
      output: {
        comments: false
      }
    }),
    ...
```

**Comment by daformat** [comment]
Importing via `import transliterate from 'transliteration';` doesn't work:

```javascript
import {transliterate} from 'transliteration';
console.log('Transiterate is ', transliterate);

// Helper functions for filtering
export const defaultMatcher = (filterText, node) => {
  return transliterate(node.name.toLowerCase()).indexOf(transliterate(filterText.toLowerCase())) !== -1;
};
```

I get `Transiterate is  undefined`in my console.

**Comment by daformat** [comment]
I couldn't get the babel transpiled import to work neitheir, that's why I chose to import the ES6 source.

From what I can tell webpack2's UglifyJS plugin has no trouble with ES6, I just hit this problem using transliterate.

Here is a copy of the deps I currently have on the `use-transliterate-library` branch:

```javascript
  "dependencies": {
    "axios": "^0.15.3",
    "compression": "^1.6.2",
    "express": "^4.14.1",
    "immutability-helper": "^2.0.0",
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-cookie-banner": "0.0.17",
    "react-dom": "^15.4.2",
    "react-ga": "^2.1.2",
    "react-helmet": "^4.0.0",
    "react-router": "^3.0.2",
    "react-treebeard": "^1.1.4",
    "smoothscroll": "^0.3.0",
    "transliteration": "^1.5.2"
  },
  "devDependencies": {
    "@types/axios": "^0.9.32",
    "@types/react": "^15.0.6",
    "@types/react-addons-test-utils": "^0.14.15",
    "@types/react-dom": "^0.14.22",
    "@types/react-router": "^3.0.0",
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.13.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-istanbul": "^3.1.2",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.2.0",
    "babel-preset-react": "^6.1.18",
    "browser-sync": "^2.18.7",
    "browser-sync-spa": "^1.0.3",
    "css-loader": "^0.26.1",
    "del": "^2.0.2",
    "es6-shim": "^0.35.0",
    "eslint": "^3.14.1",
    "eslint-config-xo-react": "^0.10.0",
    "eslint-config-xo-space": "^0.15.0",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-babel": "^4.0.1",
    "eslint-plugin-react": "^6.9.0",
    "extract-text-webpack-plugin": "^2.0.0-beta",
    "gulp": "github:gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb",
    "gulp-filter": "^4.0.0",
    "gulp-hub": "github:frankwallis/gulp-hub#d461b9c700df9010d0a8694e4af1fb96d9f38bf4",
    "gulp-sass": "^2.1.1",
    "gulp-util": "^3.0.7",
    "html-webpack-plugin": "^2.28.0",
    "jasmine": "^2.4.1",
    "json-loader": "^0.5.4",
    "karma": "^1.4.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-junit-reporter": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-phantomjs-shim": "^1.1.2",
    "karma-webpack": "^2.0.2",
    "mark.js": "julmot/mark.js",
    "node-sass": "^4.5.0",
    "phantomjs-prebuilt": "^2.1.6",
    "postcss-loader": "^1.2.2",
    "react-addons-test-utils": "^15.0.1",
    "react-hot-loader": "^1.3.0",
    "react-icons": "^2.2.3",
    "sass-loader": "^4.1.1",
    "style-loader": "^0.13.0",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-fail-plugin": "^1.0.5",
    "webpack-hot-middleware": "^2.16.1"
  }
```

**Comment by andyhu** [comment]
Have you tried 1.5.3?

**Comment by daformat** [comment]
Thanks for trying!

So, updating to 1.5.3 I can import directly from transliteration, but **using a named import** (not the default suggested in previous replies, which will still get me `undefined`):
`import {transliterate} from 'transliteration';`

However I still have the same issue with my build process. (`ERROR in /vendor-27e5075aef1f7d0449f6.js from UglifyJs
SyntaxError: Unexpected token: name (codemap) [/vendor-27e5075aef1f7d0449f6.js:35825,4]`

Are you successfully uglifying it via webpack's plugin on your end?

If it's easier for you I'm happy to do a quick skype so I can share my screen with you and we can investigate further.

**Comment by andyhu** [comment]
Hmm, it's kind of weird. Can you check this link below and set `mangle: false` in the webpack settings and see if it works?
http://stackoverflow.com/questions/30322921/webpack-optimize-with-uglifyjs-plugin-causes-runtime-error
I also created a test repo. If it still doesn't work, I wonder if you could upload your config to this repo? https://github.com/andyhu/test-transliteraion. I have already invited you as a collaberator. I've been travelling all day by train and there isn't much battery left. I'll get back to you when I reach home.

**Comment by daformat** [comment]
Wow, thanks for being proactive like you are! I already tried setting `mangle` to false with no success. I'm cloning your test repo.

Have a nice train trip!

**Comment by andyhu** [comment]
I've got a clue why it doesn't work now. UglifyJS can't recognize some ES6 grammar like the 'let' keyword and arrow functions. babel-loader seems also missing, and even if it's not, in a real project node_modules is usually excluded. That's where the issue occurred.

**Comment by andyhu** [comment]
I have updated test-transliteration repo and now `npm run build` is working.

**Comment by daformat** [comment]
Ok, that could explain things, I indeed was excluding the node_modules folder for babel_loader, here is the full webpack-dist.conf.js I'm using on my own project:

```
const webpack = require('webpack');
const conf = require('./gulp.conf');
const path = require('path');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const FailPlugin = require('webpack-fail-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const pkg = require('../package.json');
const autoprefixer = require('autoprefixer');

const deps = Object.keys(pkg.dependencies);
const filteredOutDeps = ['express', 'compression'];
for (let i = 0; i < filteredOutDeps.length; i++) {
  const pos = deps.indexOf(filteredOutDeps[i]);
  if (pos > -1) {
    deps.splice(pos, 1);
  }
}

console.log('Dist dependencies:', deps);

module.exports = {
  module: {
    loaders: [
      {
        test: /.json$/,
        loaders: [
          'json-loader'
        ]
      },
      {
        test: /.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
        enforce: 'pre'
      },
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader', publicPath: '/'})
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: [
          'babel-loader'
        ]
      }
    ]
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    FailPlugin,
    new HtmlWebpackPlugin({
      template: conf.path.src('index.html')
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        unused: true,
        dead_code: true // eslint-disable-line camelcase
      },
      mangle: false,
      output: {
        comments: false
      }
    }),
    new ExtractTextPlugin('/index-[contenthash].css'),
    new webpack.optimize.CommonsChunkPlugin({name: 'vendor'}),
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: () => [autoprefixer],
        sassLoader: {
          includePaths: [path.resolve(__dirname, 'src', 'scss')]
        },
        context: '/'
      }
    })
  ],
  output: {
    path: path.join(process.cwd(), conf.paths.dist),
    filename: '/[name]-[hash].js'
  },
  entry: {
    app: `./${conf.path.src('index')}`,
    vendor: deps
  }
};

```

**Comment by daformat** [comment]
Not excluding the node_modules folder for babel-loader throws quite a few errors for the other deps I'm using and it still gets me the error about `codemap`

```
ERROR in ./~/react-treebeard/index.js
Module build failed: ReferenceError: [BABEL] /Users/mat/Sites/cpmivg-react/node_modules/react-treebeard/index.js: Using removed Babel 5 option: /Users/mat/Sites/cpmivg-react/node_modules/react-treebeard/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/mat/Sites/cpmivg-react/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/mat/Sites/cpmivg-react/node_modules/babel-loader/lib/index.js:133:12)
 @ multi axios immutability-helper lodash react react-addons-css-transition-group react-cookie-banner react-dom react-ga react-helmet react-router react-treebeard smoothscroll transliteration

ERROR in ./~/radium/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/mat/Sites/cpmivg-react/node_modules/radium/.babelrc" at 0, attempted to resolve relative to "/Users/mat/Sites/cpmivg-react/node_modules/radium"
    at /Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:36)
    at OptionManager.init (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/mat/Sites/cpmivg-react/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/mat/Sites/cpmivg-react/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/mat/Sites/cpmivg-react/node_modules/babel-loader/lib/index.js:133:12)
 @ ./src/app/codes/toc/toc.js 13:14-31
 @ ./src/app/codes/code.js
 @ ./src/routes.js
 @ ./src/index.js

ERROR in /vendor-0d3bcb80e431118c8693.js from UglifyJs
SyntaxError: Unexpected token: name (codemap) [/vendor-0d3bcb80e431118c8693.js:25886,4]
```

**Comment by andyhu** [comment]
How about ignoring `/node_modules\/(?!transliteration\/)/`?
I know it's a bit hacky...

**Comment by andyhu** [comment]
By the way, your code is for browser right? How about using it in this way:
```js
import { transliterate } from 'transliteration/lib/browser/transliteration';
```
It is fully transpiled so it should cause no issues for uglifyjs.

**Comment by daformat** [comment]
As said previously, importing this way gets me `Transliterate is  undefined`, importing any other way than from your es6 source gets me the same error.

I'm confused about the ignore you're suggesting, should I edit something else than my rule for babel-loader? I tried using the test regex you gave for babel-loader with no success (same error about codemap)

**Comment by andyhu** [comment]
Please check `test-transliteration`. I've updated webpack config file

**Comment by andyhu** [comment]
Importing from `transliteration/lib/browser/transliteration` seems not working, please revert back by using `transliteration`

**Comment by daformat** [comment]
Yup I did so, so apparently I made typo copy/pasting from your comments. Copy pasting the exclude directive from test-transliteration into my webpack build configuration file did solve the issue. I now get a production build, that actually builds :)

Uploading to a test server right now.

**Comment by andyhu** [comment]
Great, let me know if there's more issues. I think I need to address this issue in README file, while for long term maybe I'll still need to refactor the code a bit to find a better solution.

**Comment by daformat** [comment]
Woops, sorry for the joy, I was on my master branch (it's 6.30 am here, so my brain is still not 100% awake).

Sadly, I still get the same error in my build.

**Comment by daformat** [comment]
Here is my full webpack file:

```
const webpack = require('webpack');
const conf = require('./gulp.conf');
const path = require('path');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const FailPlugin = require('webpack-fail-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const pkg = require('../package.json');
const autoprefixer = require('autoprefixer');

const deps = Object.keys(pkg.dependencies);
const filteredOutDeps = ['express', 'compression'];
for (let i = 0; i < filteredOutDeps.length; i++) {
  const pos = deps.indexOf(filteredOutDeps[i]);
  if (pos > -1) {
    deps.splice(pos, 1);
  }
}

console.log('Dist dependencies:', deps);

module.exports = {
  module: {
    loaders: [
      {
        test: /.json$/,
        loaders: [
          'json-loader'
        ]
      },
      {
        test: /.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader',
        enforce: 'pre'
      },
      {
        test: /(\.scss|\.css)$/,
        loader: ExtractTextPlugin.extract({fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader', publicPath: '/'})
      },
      {
        test: /\.js$/,
        exclude: /node_modules\/(?!transliteration\/)/,
        loaders: [
          'babel-loader'
        ]
      }
    ]
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    FailPlugin,
    new HtmlWebpackPlugin({
      template: conf.path.src('index.html')
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        unused: true,
        dead_code: true // eslint-disable-line camelcase
      },
      mangle: false,
      output: {
        comments: false
      }
    }),
    new ExtractTextPlugin('/index-[contenthash].css'),
    new webpack.optimize.CommonsChunkPlugin({name: 'vendor'}),
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: () => [autoprefixer],
        sassLoader: {
          includePaths: [path.resolve(__dirname, 'src', 'scss')]
        },
        context: '/'
      }
    })
  ],
  output: {
    path: path.join(process.cwd(), conf.paths.dist),
    filename: '/[name]-[hash].js'
  },
  entry: {
    app: `./${conf.path.src('index')}`,
    vendor: deps
  }
};

```

**Comment by daformat** [comment]
Ad my .babelrc:

```
{
  "presets": [
    "react",
    "es2015"
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    },
    "production": {
      "presets": [
        [
          "es2015",
          {
            "modules": false
          }
        ]
      ]
    }
  }
}

```

**Comment by daformat** [comment]
So it might have something to do with my "modules": false directive... Don't know how to handle this edge case

**Comment by andyhu** [comment]
So what's the error message now?

**Comment by daformat** [comment]
Still the same message about codemap

**Comment by andyhu** [comment]
I'm not sure .babelrc works or not. Can you try to use queries in webpack config file like in test-transliteration repo instead of using .babelrc?
I've updated that repo for your reference (with module: false)

**Comment by daformat** [comment]
Ok, I might try this first: https://twitter.com/dan_abramov/status/830776755204063232
Will let you know as soon as I have a chance to do it.

Thanks a lot for the help. Though on my end, there's no rush fixing it, as my visitors and my content are french, the basic transliteration helper I wrote works fine for the time being.

**Comment by kachkaev** [comment]
Hi guys,

I tried `transliteration` inside [`create-react-app`](https://github.com/facebookincubator/create-react-app) today and got this during `npm run build` unfortunately:

```
Failed to compile.

static/js/main.bca95e50.js from UglifyJs
Unexpected token: name (charmap) [./~/transliteration/lib/node/transliterate.js:16,0][static/js/main.bca95e50.js:8
5185,4]
```

There seems no way to overcome this, because `create-react-app` does not give users access to `.babelrc`. The solution looks simple: just get rid of `let` and `cost` in `lib/node/*` to make webpack happy. @andyhu could you please look into this? 🙏

**Comment by kachkaev** [comment]
Tried adding `es2015` to `.babelrc`, then `npm run build` this module and finally `npm link` to my copy of `create-react-app`. It finally built too! https://github.com/andyhu/transliteration/pull/44 might work as a fix therefore – please consider merging or just copying the idea from there.

**Comment by martyan** [comment]
Hi Folks, any updadte on this? 

I'm using es2015 preset, but it doesn't solve the problem.

**Comment by core-process** [comment]
I published the following package as a temporary workaround: https://www.npmjs.com/package/transliterations (clone of transliteration, but using es2015 preset)

**Comment by madconst** [comment]
I confirm, create-react-app build script fails with 'transliteration' but succeed with 'transliterations'. The error with 'transliteration is:
![image](https://user-images.githubusercontent.com/10620102/35217282-ad9207cc-ff7b-11e7-9cbb-0f93c28c9f84.png)
This is because of 'let' keyword (not es5). Explanation is here:
bit.ly/2tRViJ9

(npm modules must be es5-compatible)

I switched to 'transliterations' until this issue gets fixed.

**Comment by core-process** [comment]
Would love to see some progress on this matter. I see more and more traction to my clone, which is OK, but was not intended initially. @andyhu could you please let us know if you intent to fix this issue? I know we are not paying customers, but a fix would be very simple and it does not hurt. ;-)

**Comment by andyhu** [comment]
Sorry guys for keep you waiting. I've been really busy. I'm planning to make multiple builds for different environment. Will update soon

**Comment by core-process** [comment]
@andyhu looking forward to!!!

**Comment by ogonkov** [comment]
Did you try explicitly set own `.babelrc`? I feel that problem with the one in root of node package, that used by project instead own

**Comment by andyhu** [comment]
@ogonkov Yes, I've added a .npmignore file as #68 suggested. Now with version 1.6.5 I think the issue should be solved.

**Comment by coolswood** [comment]
@andyhu I'am using `1.6.6` version, but I still have a problem with building production.
Failed to minify the code from this file: 
`Failed to minify the code from this file: ./node_modules/transliteration/lib/node/transliterate.js:16 `

**Comment by aksel** [comment]
Instead of importing directly from transliteration, import the lib that targets your platform. E.g., on browser, import transliteration/lib/browser/transliteration

This fixes the issue! :smile:

**Comment by lastonoga** [comment]
@andyhu  Same..

```
ERROR in 4.a12551d22b71bfc4529a.chunk.js from UglifyJs
Unexpected token: name (configOptions) [./~/transliteration/lib/node/slugify.js:23,0][4.a12551d22b71bfc4529a.chunk.js:77,4]
```

**Comment by zhshch9527** [comment]
https://github.com/sorrycc/blog/issues/68
I configured like this:
`
export default {
extraBabelIncludes:["node_modules/transliteration"],
}
`
Special designation converted to es5,and `npm run build` works

**Comment by dzcpy** [comment]
Hi guys, please try v2 version. Now this issue should be fixed
